### ISSUE TITLE
Button not showing / Muting block breaking sounds

### ISSUE THREAD

**Issue by Synth52** [PTOM76/mod-volume-options#4]
When i equip this mod, sometimes the option to change the sounds doesnt show up whatsoever, and every time i equip it, all of the block breaking sounds are muted regardless of what i break

**Comment by StarOfChorusim** [comment]
Throwing my two cents in on this as well. It's shame because it seems like such a handy QoL mod. 
- I do have the button.
- But the sounds from the base game are muted with no way to fix it from what I can tell. I hope this can be fixed because hooowee some of the horror mods I play with are loud as sin.
